# .github/workflows/deploy-vercel.yml
name: Deploy to Vercel

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.NEXT_VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.NEXT_VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
